CoreSphere\StaticBundle\Entity\Page:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: { fields: slug }
    properties:
        title:
            - NotBlank: ~
            - MinLength: 2
            - MaxLength: 255
        content:
            - NotBlank: ~
            - MinLength: 10
        slug:
            - NotBlank: ~
            - MaxLength: 255
            - Regex: "~^[a-z_-]+$~i"