CoreSphere\StaticBundle\Entity\Page:
    properties:
        title:
            - NotBlank: ~
            - MinLength: 10
            - MaxLength: 255
        content:
            - NotBlank: ~
            - MinLength: 10
        slug:
            - NotBlank: ~
            - MaxLength: 255
            - Regex: "~^[a-z_-]+$~i"