imports:
    - { resource: config_dev.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.filesystem
        default_locale: en
    translator:
        fallback: en
web_profiler:
    toolbar: false
    intercept_redirects: false

doctrine:
    dbal:
        dbname: %database_name%_test
 