CoreSphere\StaticBundle\Entity\Page:
  type: entity
  table: null
  fields:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
    title:
      type: string
      length: '255'
    content:
      type: text
    createdAt:
      type: datetime
    publishedAt:
      type: datetime
      nullable: true
    updatedAt:
      type: datetime
    slug:
      type: string
      length: 255
  lifecycleCallbacks:
    preUpdate: [ updated ]
